name: next13-node18-template
description: App Description
ignoreFiles: .git node_modules
modules:
- name: template
  language: nodejs18.x
  web: express
  description: Module description
  functions:
  - name: entry
    entry: entry.js
    description: the entry point for the function